### ISSUE TITLE
Crash in imageset format: thread 'main' panicked at 'attempt to multiply with overflow'

### ISSUE THREAD

**Issue by CJLove** [yeastplume/aloevera#14]
Palette png and tileset png were both generated from Piskel.  Crash observed with your release build on Linux and with aloevera built from source (debug).

Steps to reproduce:
```
        aloevera create project choppertest.av
	aloevera -p choppertest.av palette import palette palette.png
	aloevera -p choppertest.av imageset import chopper_tile_imageset 8 8 tileset.png
	aloevera -p choppertest.av imageset format chopper_tile_imageset palette 4
	aloevera -p choppertest.av asm -f bin . select chopper_tile_imageset TILES.BIN
```

Output:
```
aloevera create project choppertest.av
20200516 18:34:22.476 INFO aloevera - This is Aloevera version 0.2.1, built for x86_64-unknown-linux-gnu by rustc 1.43.1 (8d69840ab 2020-05-04).
20200516 18:34:22.477 INFO aloevera::cmd::create::command - Creating new project file at: choppertest.av
20200516 18:34:22.477 INFO aloevera - Command 'create' completed successfully
20200516 18:34:22.477 INFO aloevera - Finished
aloevera -p choppertest.av palette import palette ../assets/palette.png
20200516 18:34:22.611 INFO aloevera - This is Aloevera version 0.2.1, built for x86_64-unknown-linux-gnu by rustc 1.43.1 (8d69840ab 2020-05-04).
20200516 18:34:22.612 INFO aloevera_vera::palette - Creating new palette from image data
20200516 18:34:22.615 INFO aloevera_vera::palette - Palette creation successful
20200516 18:34:22.615 INFO aloevera::cmd::palette::command - Inserting palette into project: choppertest.av
20200516 18:34:22.621 INFO aloevera - Command 'palette' completed successfully
20200516 18:34:22.621 INFO aloevera - Finished
aloevera -p choppertest.av imageset import chopper_tile_imageset 8 8 ../assets/tileset.png
20200516 18:34:22.753 INFO aloevera - This is Aloevera version 0.2.1, built for x86_64-unknown-linux-gnu by rustc 1.43.1 (8d69840ab 2020-05-04).
8, 8
20200516 18:34:22.770 INFO aloevera_vera::png_util - Parsing 128 frames
20200516 18:34:22.778 INFO aloevera_vera::imageset - Image parsed successfully
20200516 18:34:22.849 INFO aloevera - Command 'imageset' completed successfully
20200516 18:34:22.849 INFO aloevera - Finished
aloevera -p choppertest.av imageset format chopper_tile_imageset palette 4
20200516 18:34:22.971 INFO aloevera - This is Aloevera version 0.2.1, built for x86_64-unknown-linux-gnu by rustc 1.43.1 (8d69840ab 2020-05-04).
20200516 18:34:23.014 INFO aloevera_vera::imageset - Formatting imageset chopper_tile_imageset to palette at depth of 4

20200516 18:34:23.161 ERROR aloevera_util::logger - 
thread 'main' panicked at 'attempt to multiply with overflow': /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ops/arith.rs:316stack backtrace:
   0: aloevera_util::logger::send_panic_to_log::{{closure}}
             at util/src/logger.rs:316
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   2: rust_begin_unwind
             at src/libstd/panicking.rs:378
   3: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   4: core::panicking::panic
             at src/libcore/panicking.rs:52
   5: <usize as core::ops::arith::Mul>::mul
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ops/arith.rs:316
   6: core::ops::function::FnMut::call_mut
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ops/function.rs:154
   7: core::iter::adapters::map_fold::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/iter/adapters/mod.rs:772
   8: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/iter/traits/iterator.rs:2001
   9: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/iter/traits/iterator.rs:1877
  10: core::iter::traits::iterator::Iterator::fold
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/iter/traits/iterator.rs:2004
  11: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/iter/adapters/mod.rs:812
  12: <usize as core::iter::traits::accum::Product>::product
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/iter/traits/accum.rs:55
  13: core::iter::traits::iterator::Iterator::product
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/iter/traits/iterator.rs:2796
  14: permutate::Permutator<T>::new
             at /home/love/.cargo/registry/src/github.com-1ecc6299db9ec823/permutate-0.3.2/src/lib.rs:159
  15: aloevera_vera::imageset::find_optimal_range
             at vera/src/imageset.rs:615
  16: aloevera_vera::imageset::VeraImageSet::format_indices
             at vera/src/imageset.rs:435
  17: aloevera::cmd::imageset::command::imageset_format
             at src/cmd/imageset/command.rs:77
  18: aloevera::cmd::imageset::parse::execute_imageset_command
             at src/cmd/imageset/parse.rs:82
  19: aloevera::cmd::execute::parse_and_execute
             at src/cmd/execute.rs:28
  20: aloevera::cmd::execute::execute_command
             at src/cmd/execute.rs:39
  21: aloevera::real_main
             at src/bin/aloevera.rs:87
  22: aloevera::main
             at src/bin/aloevera.rs:70
  23: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  24: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  26: std::panicking::try
             at src/libstd/panicking.rs:281
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  27: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  28: main
  29: __libc_start_main
  30: _start

Thread 'main' panicked with message:
"attempt to multiply with overflow"
See aloevera.log for further details.

```

Palette and tileset png files and aloevera.log are attached.

**Comment by CJLove** [comment]
[aloevera.log](https://github.com/yeastplume/aloevera/files/4639517/aloevera.log)
Palette:
![palette](https://user-images.githubusercontent.com/1477399/82133745-639ebe80-97a4-11ea-9ff7-322f33623a3c.png)
Tileset:
![tileset](https://user-images.githubusercontent.com/1477399/82133752-69949f80-97a4-11ea-8d1c-fda070803852.png)

**Comment by CJLove** [comment]
The problem may be related to the fact that the palette.png exported from Piskel was 16x16 though there were only 16 color entries (this was my bad in creating the palette.png since I couldn't import a palette as a .gpl file  as described in issue #13). When I fixed the image size to be 16x1 and re-exported the palette.png then aloevera ran fine.  It would be great to report errors like this in palette png files.

**Comment by yeastplume** [comment]
Thanks for reporting this, this should definitely be throwing a proper error so will look into it and fix

**Comment by yeastplume** [comment]
Turns out this was a bug and the original palette with 16x16 entries should have been accepted. I've just done a 0.2.2 release that should address the issue, would you be able to do a quick test?

**Comment by CJLove** [comment]
Confirmed that the crash is fixed in the new release.  Thanks for the timely fix!  BTW: I did notice that the new release still reports itself as version v0.2.1.

**Comment by yeastplume** [comment]
Thanks, rebuilt the release to fix the versioning.
